CREATE TABLE todo (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(200) NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

